# Generated by Django 5.0.2 on 2025-04-01 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('下請け', '下請け'), ('正社員', '正社員'), ('管理', '管理')], default='正社員', max_length=50, verbose_name='雇用形態')),
                ('fullname', models.CharField(blank=True, max_length=20, verbose_name='お名前')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='携帯電話')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='現役中')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='現場')),
                ('client', models.CharField(max_length=255, verbose_name='取引先')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('color', models.CharField(choices=[('#808080', '灰色'), ('#ff6961', '赤色'), ('#ffb480', '橙色'), ('#f8f38d', '黄色'), ('#42d6a4', '緑色'), ('#08cad1', '水色'), ('#59adf6', '青色'), ('#9d94ff', '紫色'), ('#c780e8', '桃色')], max_length=30, verbose_name='現場色')),
                ('job_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='作業内容')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('start_date', models.DateTimeField(verbose_name='作業開始日')),
                ('end_date', models.DateTimeField(verbose_name='作業終了日')),
                ('finished', models.BooleanField(default=False, verbose_name='終了')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('attendees', models.ManyToManyField(blank=True, related_name='attendees', to='manager_app.profile')),
                ('head_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_person', to='manager_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=10, verbose_name='距離')),
                ('highway_start', models.CharField(blank=True, max_length=100, verbose_name='高速乗り')),
                ('highway_end', models.CharField(blank=True, max_length=100, verbose_name='高速降り')),
                ('highway_payment', models.CharField(blank=True, choices=[('現金', '現金'), ('カード', 'カード'), ('電子マネー', '電子マネー'), ('会社ETC', '会社ETC'), ('無', '無')], max_length=50, verbose_name='高速料金')),
                ('select_types', models.CharField(blank=True, choices=[('請負', '請負'), ('常傭', '常傭')], max_length=50, verbose_name='請負乗用')),
                ('parking', models.CharField(blank=True, max_length=100, verbose_name='駐車料金')),
                ('hotel', models.CharField(blank=True, max_length=100, verbose_name='宿泊料金')),
                ('other_payment', models.CharField(blank=True, max_length=100, verbose_name='その他支払い')),
                ('other_payment_amount', models.CharField(blank=True, max_length=100, verbose_name='その他支払い金額')),
                ('daily_details', models.CharField(blank=True, max_length=500, verbose_name='作業内容')),
                ('shift', models.CharField(choices=[('日勤', '日勤'), ('夜勤', '夜勤')], default='日勤', max_length=50, verbose_name='日勤夜勤')),
                ('daily_note', models.CharField(blank=True, max_length=500, verbose_name='備考')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('working_date', models.DateField(blank=True, null=True, verbose_name='作業日')),
                ('kentaikyo', models.BooleanField(default=False, verbose_name='建退共')),
                ('start_time', models.TimeField(verbose_name='作業開始時間')),
                ('end_time', models.TimeField(verbose_name='作業終了時間')),
                ('break_time', models.CharField(blank=True, max_length=10, verbose_name='休憩時間')),
                ('genba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genba', to='manager_app.genba')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='manager_app.profile')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to='manager_app.profile')),
                ('workers', models.ManyToManyField(blank=True, related_name='workers', to='manager_app.profile')),
            ],
        ),
    ]
